server:
  port: 8081
limit:
  minMoney: 0.01
  maxMoney: 9999
  description: 最少要发 ${limit.minMoney} 元
  
spring:
  datasource:
       drive-class-name: con.mysql.cj.jdbc.Driver
       url: jdbc:mysql://127.0.0.1:3306/luckymoney
       username: root
       password: 
  jpa:
       hibernate:
          ddl-auto: create
       show-sql: true